/* ============================================================
   REALTOR SITE TEMPLATE — Listings data layer
   Seed data ships with the site; the admin panel saves edits
   to localStorage, which overrides the seed for this browser.
   ============================================================ */

const HR_STORE_KEY = "hr_listings_v1";

/* Listings seed is generated by build.py from site.config.json.
   The admin panel persists edits to localStorage. */
const HR_SEED_LISTINGS = {{LISTINGS_SEED}};

const HRData = {
  getAll() {
    try {
      const raw = localStorage.getItem(HR_STORE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed)) return parsed;
      }
    } catch (e) { /* corrupted store — fall back to seed */ }
    return structuredClone(HR_SEED_LISTINGS);
  },

  saveAll(listings) {
    localStorage.setItem(HR_STORE_KEY, JSON.stringify(listings));
  },

  reset() {
    localStorage.removeItem(HR_STORE_KEY);
  },

  hasCustomData() {
    return localStorage.getItem(HR_STORE_KEY) !== null;
  },

  statusLabel(status) {
    return { "for-sale": "For Sale", "pending": "Pending", "sold": "Sold" }[status] || status;
  },

  formatPrice(listing) {
    if (listing.status === "sold") {
      return listing.price ? "Sold · " + HRData.money(listing.price) : "Sold";
    }
    return listing.price ? HRData.money(listing.price) : "Price on request";
  },

  money(n) {
    return new Intl.NumberFormat("en-US", {
      style: "currency", currency: "USD", maximumFractionDigits: 0
    }).format(n);
  }
};
